= Title Slide
:revealjsdir: .
:revealjs_theme: sky
//*:revealjs_width: 1600*/
:docinfo: private
:customcss: styles.css
:source-highlighter: highlight.js
//:revealjs_preloadIframes: false
:viewDistance: 1

//== Which Server?
//[pass]
//++++
//<div style="display:flex">
//    <div style="flex:1; text-align:left; margin-left:200px">
//       <input type="radio" name="endpointOptions" value="localhost"> localhost<br>
//       <input type="radio" name="endpointOptions" value="AWS"> AWS<br>
//    </div>
//</div>
//++++

[.columns]
== What will it print?

[.column-is-four-fifths]
[source, java]
--
String[] stringArray = {"one", "two", "three"};
var stringList = Arrays.asList(stringArray);

int[] intArray = {1, 2, 3};
var intList = Arrays.asList(intArray);

System.out.print(stringList.contains("one") + ", ");
System.out.print(intList.contains(1));
--

[.column]
[pass]
++++
<div class="votingQuestion">question1:true,false;false,true;true,true</div>
++++

== What might it print?

[source, java]
--
String[] stringArray = {"three", "two", "one"};
var stringList = Arrays.asList(stringArray);

int[] intArray = {1, 2, 3};
var intList = Arrays.asList(intArray);

System.out.print(stringList.contains("one") + ", ");
System.out.print(intList.contains(1));
--

[.columns]
== What won't it print?

[.column-is-four-fifths]
[source, java]
--
String[] stringArray = {"three", "two", "one"};
var stringList = Arrays.asList(stringArray);

int[] intArray = {1, 2, 3};
var intList = Arrays.asList(intArray);

System.out.print(stringList.contains("one") + ", ");
System.out.print(intList.contains(1));
--

[.column]
[pass]
++++
<div class="votingQuestion">question2:yes,no;no,yes;yes,yes</div>
++++
