= Title Slide
:revealjsdir: .
:revealjs_theme: sky
//*:revealjs_width: 1600*/
:docinfo: private
:customcss: styles.css
:source-highlighter: highlight.js
//:revealjs_preloadIframes: false
:viewDistance: 1

//== Which Server?
//[pass]
//++++
//<div style="display:flex">
//    <div style="flex:1; text-align:left; margin-left:200px">
//       <input type="radio" name="endpointOptions" value="localhost"> localhost<br>
//       <input type="radio" name="endpointOptions" value="AWS"> AWS<br>
//    </div>
//</div>
//++++

[.columns]
== What will it print?

[.column-is-four-fifths]
[source, java]
--
String[] stringArray = {"one", "two", "three"};
var stringList = Arrays.asList(stringArray);

int[] intArray = {1, 2, 3};
var intList = Arrays.asList(intArray);

System.out.print(stringList.contains("one") + ", ");
System.out.print(intList.contains(1));
--

[.column]
[pass]
++++
<div id="question1">No connection to server</div>
<script>
    function postSlide(question, concatenatedAnswerTexts) {
        const url = 'http://localhost:8080/slides';

        const answerTexts = concatenatedAnswerTexts.split(';');

        const slide = {
            question: question,
            answers: answerTexts.map(text => ({ text, votes: 0 }))
        };

        const requestOptions = {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(slide)
        };

        fetch(url, requestOptions)
            .then(response => {
                if (!response.ok) {
                    throw new Error('Network error');
                }
                // return response.json();
            })
            .then(data => {
                document.getElementById("question1").innerHTML='<iframe id="question1" src="http://localhost:8080/client.html?question=question1" width="800" height="300" allowfullscreen></iframe>';
                console.log('Success:', data);
            })
            .catch(error => {
                console.error('Fetch failed:', error);
            });
    }

    postSlide('question1','true,false;false,true;true,true');
</script>
++++

== What might it print?

[source, java]
--
String[] stringArray = {"three", "two", "one"};
var stringList = Arrays.asList(stringArray);

int[] intArray = {1, 2, 3};
var intList = Arrays.asList(intArray);

System.out.print(stringList.contains("one") + ", ");
System.out.print(intList.contains(1));
--

[.columns]
== What won't it print?

[.column-is-four-fifths]
[source, java]
--
String[] stringArray = {"three", "two", "one"};
var stringList = Arrays.asList(stringArray);

int[] intArray = {1, 2, 3};
var intList = Arrays.asList(intArray);

System.out.print(stringList.contains("one") + ", ");
System.out.print(intList.contains(1));
--

[.column]
[pass]
++++
<div id="question2">No connection to server</div>
<script>
    function postSlide(question, concatenatedAnswerTexts) {
        const url = 'http://localhost:8080/slides';

        const answerTexts = concatenatedAnswerTexts.split(';');

        const slide = {
            question: question,
            answers: answerTexts.map(text => ({ text, votes: 0 }))
        };

        const requestOptions = {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(slide)
        };

        fetch(url, requestOptions)
            .then(response => {
                if (!response.ok) {
                    throw new Error('Network error');
                }
                // return response.json();
            })
            .then(data => {
                document.getElementById("question2").innerHTML='<iframe id="question2" src="http://localhost:8080/client.html?question=question2" width="800" height="300" allowfullscreen></iframe>';
                console.log('Success:', data);
            })
            .catch(error => {
                console.error('Fetch failed:', error);
            });
    }

    postSlide('question2','yes,no;no,yes;yes,yes');

</script>
++++
