= Title Slide
:revealjsdir: .
:revealjs_theme: sky
//*:revealjs_width: 1600*/
:docinfo: private
:customcss: styles.css
:source-highlighter: highlight.js
//:revealjs_preloadIframes: false
:viewDistance: 1

//== Which Server?
//[pass]
//++++
//<div style="display:flex">
//    <div style="flex:1; text-align:left; margin-left:200px">
//       <input type="radio" name="endpointOptions" value="localhost"> localhost<br>
//       <input type="radio" name="endpointOptions" value="AWS"> AWS<br>
//    </div>
//</div>
//++++

[.columns]
== What will it print?

[.column-is-four-fifths]
[source, java]
--
String[] stringArray = {"one", "two", "three"};
var stringList = Arrays.asList(stringArray);

int[] intArray = {1, 2, 3};
var intList = Arrays.asList(intArray);

System.out.print(stringList.contains("one") + ", ");
System.out.print(intList.contains(1));
--

[.column]
[pass]
++++
<script>fetch("http://localhost:8080/question1/setColumnLabels?labels=true%2Cfalse;false%2Ctrue;true%2Ctrue")</script>
<div><iframe id="question1" src="http://localhost:8080/index-new.html?question=question1" width="800" height="300" allowfullscreen></iframe></div>
++++

== What might it print?

[source, java]
--
String[] stringArray = {"three", "two", "one"};
var stringList = Arrays.asList(stringArray);

int[] intArray = {1, 2, 3};
var intList = Arrays.asList(intArray);

System.out.print(stringList.contains("one") + ", ");
System.out.print(intList.contains(1));
--

[.columns]
== What won't it print?

[.column-is-four-fifths]
[source, java]
--
String[] stringArray = {"three", "two", "one"};
var stringList = Arrays.asList(stringArray);

int[] intArray = {1, 2, 3};
var intList = Arrays.asList(intArray);

System.out.print(stringList.contains("one") + ", ");
System.out.print(intList.contains(1));
--

[.column]
[pass]
++++
<script>fetch("http://localhost:8080/question2/setColumnLabels?labels=yes%2Cno;no%2Cyes;yes%2Cyes")</script>
<div><iframe id="question2" src="http://localhost:8080/index-new.html?question=question2" width="800" height="300" allowfullscreen></iframe></div>
++++
